In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3])
b = np.array([3,2,4])

In [5]:
print(a*b)

[ 3  4 12]


In [6]:
a = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
a[0,0,:]

array([1, 2])

In [9]:
a[0,0,:1]=10

In [10]:
a

array([[[10,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]]])

In [11]:
a[0,0]

array([10,  2])

In [12]:
a[0,0,0]

10

In [16]:
a[:,0,1]

array([2, 6])

In [17]:
a[1,1,1]=24

In [18]:
a

array([[[10,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7, 24]]])

# Initializing matrix

In [21]:
# zero matrix
a = np.zeros((2,4),dtype = 'int32')
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [22]:
a = np.ones((2,2),dtype = 'int32')
a

array([[1, 1],
       [1, 1]], dtype=int32)

In [23]:
a = np.full((2,2,2),77)

In [24]:
a

array([[[77, 77],
        [77, 77]],

       [[77, 77],
        [77, 77]]])

In [26]:
# random matrix
np.random.rand(2,3)

array([[0.01770878, 0.99602202, 0.47160156],
       [0.93104096, 0.68128522, 0.50594611]])

In [27]:
# random matrix with int
np.random.randint(2,7, size = (3,2))

array([[5, 4],
       [5, 5],
       [4, 4]])

In [32]:
a = np.array ([[[1,2,3]]])

In [33]:
a

array([[[1, 2, 3]]])

In [36]:
np.repeat(a,3,axis= 0)

array([[[1, 2, 3]],

       [[1, 2, 3]],

       [[1, 2, 3]]])

In [46]:
a = np.ones((5,5))
print(a)
b= np.zeros((3,3))
print(b)
b[1,1]=9
print(b)
a[1:4,1:4]=b
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [50]:
a = np.array([1,2,3,4])

In [51]:
a.shape

(4,)

In [53]:
a[2]

3

In [58]:
a = np.array([[[1,2,3],[4,5,6]]])

In [59]:
a.shape

(1, 2, 3)

In [61]:
a

array([[[1, 2, 3],
        [4, 5, 6]]])